# This settings can be used to create repo level settings
repository: 
  # Name of the repo
  name: safe8
 
  # Create the repo if it is not existing
  force_create: true

  # Use a template when creating the repo
  # template: template_repo

  # This is the settings that need to be applied to all repositories in the org 
  # See https://developer.github.com/v3/repos/#edit for all available settings for a repository  
  # A short description of the repository that will show up on GitHub
  description: description of the repo
  
  # A URL with more information about the repository
  homepage: https://example.github.io/
    
  # Keep this as true for most cases
  # A lot of the policies below cannot be implemented on bare repos
  # Pass true to create an initial commit with empty README.
  auto_init: true
